### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by ronnievisser** [LKaemmerling/laravel-horizon-prometheus-exporter#10]
Hi,

Not sure what it should take yet but any plan to upgrade to PHP8.0?

thanks

**Comment by LKaemmerling** [comment]
Hey, I will look into this tomorrow Morning :) should be an easy fix

**Comment by LKaemmerling** [comment]
Hey @ronnievisser,

i just released a version with PHP 8.0 support :) It is a "patch" release (v1.1.3)

**Comment by ronnievisser** [comment]
Great news! thanks man
