### ISSUE TITLE
'Enabled' option of the config file is not evaluated

### ISSUE THREAD

**Issue by flofloflo** [LKaemmerling/laravel-horizon-prometheus-exporter#13]
Hi,
first of all thanks for sharing this package!

While testing it with a local project I noticed that the `enabled` option is only declared in the config file but changing it did not have any effect (the route was always reachable).

A quick search trough the code for any use of the option gave no results. Is the enable/disable feature still missing in this package or did I oversee something?

**Comment by LKaemmerling** [comment]
Hey @flofloflo,

thank you for the issue you are completely right! I guess I planned to add it but then I didn't add it. I opened up an MR (#14) that fixes this. Thank you!

**Comment by flofloflo** [comment]
That was fast! Thanks!
