### ISSUE TITLE
Authentication middleware on the "/metrics" API

### ISSUE THREAD

**Issue by thisismahabadi** [LKaemmerling/laravel-horizon-prometheus-exporter#26]
Hey @LKaemmerling, hope you're doing fine!

We're trying to use this package and one issue we have is that this "/metrics" API requires authentication by default, what I was thinking of is that because you're using the "api.php" file for defining the route and Laravel by default would apply "auth:api" on all of these routes defined in the "api.php".

As a workaround, what I need to do is the override the API route and manually define it again in one of my route files like the routes/web.php, but then one issue with that is for example some stuff that you're checking in the library like the 'horizon-exporter.enabled' should be manually checked again by me if I define this API and it does not sound very ideal to me.

Therefore, I was wondering if my theory is wrong and if you support a way that makes this API completely public without requiring the authentication.

**Comment by LKaemmerling** [comment]
Hey @thisismahabadi,

api.php is just the name of the file.  The package does not add an auth middleware to the endpoint except the IP whitelist. So the auth use are talking about must come from something else. I never had the case (nor knew about it) that Laravel adds middlewares because of a file name.

**Comment by thisismahabadi** [comment]
I found the issue! It appears we were setting something up after all the routes were loaded, which caused a problem with the custom route configuration.

**Comment by thisismahabadi** [comment]
I found the issue! It appears we were setting something up after all the routes were loaded, which caused a problem with the custom route configuration.
