### ISSUE TITLE
Is it possible to implement a counter using this package?

### ISSUE THREAD

**Issue by m90** [LKaemmerling/laravel-horizon-prometheus-exporter#29]
I'm using this package to export Horizon related metrics, as well as some custom gauges that I add to the `exporters` config.

I'd like to add another metric that is best modeled as a counter. Ideally, I'd like to inject a `CollectorRegistry` into my controller and then call `inc` on the metric each time the event I'd like to count happens.

However, looking through the code of the Horizon exporters I can only see gauges being used, and I also can't find any hints about how to do stateful operations like counters anywhere. My question therefore is: is it even possible / expected to use this package to have non-Gauge metrics or would I need to start using something else for these metrics?

**Comment by LKaemmerling** [comment]
Hey, this lib is based on https://github.com/PromPHP/prometheus_client_php so yes Counters can be used. Just head over to this lib, I'm sorry that i can't post you a code sample now as I'm only on my mobile phone, but i wanted to help you as fast as possible :)

**Comment by m90** [comment]
Specifically, what I struggle with is:

1. How do I acess the `CollectorRegistry` that is used by the `ExporterRepository` _without_ having to call `ExporterRepository::load()` which seems to have side effects like calling `collect` on all known exporters?
2. How do I make this Registry use a persistent storage adapter? Right now, it seems `InMemory` is hardcoded

**Comment by LKaemmerling** [comment]
@m90 You can use a middleware/service provider to get or set the CollectorRegistry via: https://github.com/LKaemmerling/laravel-horizon-prometheus-exporter/blob/master/src/Repository/ExporterRepository.php#L45 

This way you can overwrite the default InMemory Adapter.

**Comment by m90** [comment]
So what I came up with is a provider that creates the registry and also sets it for the `ExporterRepository` on boot:

```php
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Config;
use Prometheus\CollectorRegistry;
use Prometheus\Storage\Redis;
use Illuminate\Contracts\Foundation\Application;
use LKDevelopment\HorizonPrometheusExporter\Repository\ExporterRepository;


class CollectorRegistryProvider extends ServiceProvider
{
    /**
     * Register services.
     */
    public function register(): void
    {
        $this->app->bind(CollectorRegistry::class, function (Application $app) {
            return new CollectorRegistry(new Redis([
                'host' => Config::get('database.redis.metrics.host'),
                'port' => Config::get('database.redis.metrics.port'),
                'password' => Config::get('database.redis.metrics.password'),
                'timeout' => 0.1, // in seconds
                'read_timeout' => '10', // in seconds
                'persistent_connections' => false
            ]));
        }, true);
    }

    /**
     * Bootstrap services.
     */
    public function boot(): void
    {
        ExporterRepository::setRegistry(
            $this->app->make(CollectorRegistry::class),
        );
    }
}
```

The only interesting question that remains is where to register the metrics now. Defining them in my `Exporter` classes will not work as these might never have their `metrics` methods called before some other part of the application tries to increment a counter or similar. Right now I will just register in different places, but maybe I'll have a better idea soon.

In any case thanks for your support in getting this up and running.
